Use sklearn.datasets iris flower dataset to train your model using logistic regression. You need to figure out accuracy of your model and use that to predict different samples in your test dataset. In iris dataset there are 150 samples containing following features,

-Sepal Length
-Sepal Width
-Petal Length
-Petal Width

Using above 4 features you will clasify a flower in one of the three categories,

-Setosa
-Versicolour
-Virginica

In [1]:
from sklearn.datasets import load_iris
iris = load_iris()

In [2]:
dir(iris)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [4]:
iris.data[1]

array([4.9, 3. , 1.4, 0.2])

In [6]:
X = iris.data
y = iris.target

In [5]:
from sklearn.model_selection import train_test_split

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2)

In [8]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

In [10]:
model.fit(X_train,y_train)

LogisticRegression()

In [11]:
model.score(X_test,y_test)

1.0

In [12]:
y_test

array([0, 2, 0, 1, 0, 2, 2, 0, 2, 2, 0, 1, 2, 1, 0, 1, 2, 1, 2, 2, 1, 1,
       0, 2, 0, 1, 1, 0, 0, 1])

In [13]:
model.predict(X_test)

array([0, 2, 0, 1, 0, 2, 2, 0, 2, 2, 0, 1, 2, 1, 0, 1, 2, 1, 2, 2, 1, 1,
       0, 2, 0, 1, 1, 0, 0, 1])

In [14]:
iris.target[48]

np.int64(0)

In [16]:
model.predict([iris.data[48]])

array([0])

In [21]:
iris.target_names[0]

np.str_('setosa')

In [23]:
iris.target_names[1]

np.str_('versicolor')

In [22]:
iris.target_names[2]

np.str_('virginica')

In [24]:
y_pred = model.predict(X_test)

In [26]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)
cm

array([[10,  0,  0],
       [ 0, 10,  0],
       [ 0,  0, 10]])